name: git_info_plus
description: Get git information from within the Flutter application
version: 0.0.1
homepage: https://github.com/aakira/git_info_plus

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.github.aakira.git_info_plus
        pluginClass: GitInfoPlusPlugin
      ios:
        pluginClass: GitInfoPlusPlugin
